Brick-log/til-server

- build.gradle.kts
- src/api/build.gradle.kts
- src/api/src/main/kotlin/com/tenmm/tilserver/alaram/domain/Alarm.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/blog/domain/Blog.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/category/adapter/inbound/rest/GetCategoryController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/category/adapter/outbound/persistence/model/converters.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/category/domain/Category.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/common/domain/Identifier.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/common/domain/Url.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/common/utils/regex.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/draft/domain/Draft.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/domain/Post.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/user/domain/User.kt
> feat: implement domain object

- src/api/src/main/kotlin/com/tenmm/tilserver/category/adapter/outbound/GetCategoryAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/category/application/inbound/GetCategoryUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/category/application/outbound/GetCategoryPort.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/category/application/service/GetCategoryService.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/common/domain/Identifier.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/common/domain/OperationResult.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/GetPostController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/model/GetPostListResponse.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/DeletePostUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/GetPostUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/GetRecommendedPostUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/SavePostUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/model/GetPostListResult.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/model/GetPostResult.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/model/PostSaveConfirmCommand.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/model/PostSaveRequestCommand.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/model/PostSaveRequestResult.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/user/application/inbound/GetUserUseCase.kt
> define: post usecase

- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/GetPostController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/AddRecommendedPostUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/DeleteRecommendedPostUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/GetPostUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/model/GetPostMetaResult.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/model/PostSaveConfirmCommand.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/model/PostSaveRequestCommand.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/model/PostSaveRequestResult.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/domain/Post.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/user/application/inbound/GetUserUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/user/domain/User.kt
> define: add post inbound

- src/api/src/main/kotlin/com/tenmm/tilserver/user/application/inbound/CreateUserUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/user/application/inbound/ModifyUserUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/user/application/inbound/model/CreateUserCommand.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/user/domain/User.kt
> define: user use case

- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/GetPostUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/GetRecommendedPostUseCase.kt
define: define more post usecase
> define: define more post usecase

- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/DeletePostController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/GetPostController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/ModifyPostController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/RecommendedPostController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/SavePostController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/model/ConfirmUploadPostRequest.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/model/ConfirmUploadPostResponse.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/model/GetPostListResponse.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/model/ModifyPostRequest.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/model/ModifyRecommendedPostResponse.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/model/RequestUploadPostRequest.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/model/RequestUploadPostResponse.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/AddRecommendedPostUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/DeleteRecommendedPostUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/model/GetPostListResult.kt
feat: impl post domain controller
> impl post domain controller

- build.gradle.kts
- libs/protocol/build.gradle.kts
- libs/protocol/src/main/proto/Hello.proto
- settings.gradle.kts
- src/api/build.gradle.kts
- src/crawler/build.gradle.kts
- src/crawler/src/main/kotlin/com/tenm/crawler/HelloService.kt
- src/crawler/src/main/resources/application.yml
> feat: add grpc config

- src/api/src/main/kotlin/com/tenmm/tilserver/category/adapter/outbound/GetCategoryAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/category/application/service/GetCategoryService.kt
> Modified: category Service, component 추가

- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/entity/AlarmEntity.kt
- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/entity/BlogEntity.kt
- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/entity/DraftEntity.kt
- src/crawler/build.gradle.kts
- src/crawler/src/main/kotlin/com/tenmm/crawler/CrawlerApplication.kt
- src/crawler/src/main/kotlin/com/tenmm/crawler/HelloService.kt
- src/crawler/src/main/kotlin/com/tenmm/crawler/grpc/config/GrpcProperties.kt
- src/crawler/src/main/kotlin/com/tenmm/crawler/grpc/config/GrpcServer.kt
- src/crawler/src/main/resources/application.yml
implement grpc server
can use grpc
-
> feat: impl grpc

- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/entity/ParsedPostEntity.kt
- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/entity/PostEntity.kt
- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/repository/ParsedPostRepository.kt
- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/repository/PostRepository.kt
- libs/storage/src/main/resources/application-storage-local.yml
- libs/storage/src/main/resources/sql/database_ddl.sql
fix: add new column post identifier and impl new redis entity
-
> fix: add new column post identifier and impl new redis entity

- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/entity/RecommendPostEntity.kt
- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/repository/RecommendPostRepository.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/RecommendedPostController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/outbound/RecommendedPostAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/DeleteRecommendedPostUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/GetPostUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/outbound/AddRecommendedPostPort.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/outbound/GetRecommendedPostPort.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/service/GetPostService.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/service/RecommendedPostService.kt
- src/api/src/test/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/GetPostControllerTest.kt
feat: implement recommended post service layer
support recommended post service
TBD
> feat: implement recommended post service layer

- libs/protocol/src/main/proto/Crawler.proto
- src/crawler/build.gradle.kts
- src/crawler/src/main/kotlin/com/tenmm/crawler/CrawlerService.kt
> Feature/impl crawler (테스트 필요)

- src/api/src/main/kotlin/com/tenmm/tilserver/draft/adapter/inbound/controller/GetDraftController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/draft/adapter/inbound/controller/SaveDraftController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/draft/adapter/inbound/controller/SyncDraftController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/draft/adapter/inbound/controller/model/GetDraftResponse.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/draft/adapter/inbound/controller/model/SaveDraftRequest.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/draft/adapter/inbound/controller/model/SaveDraftResponse.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/draft/adapter/inbound/controller/model/SyncDraftRequest.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/draft/adapter/inbound/controller/model/SyncDraftResponse.kt
> Modified; swagger 설명 추가 (tag로 묶기, api 설명, response설명, model 설명)

- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/repository/PostRepository.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/common/domain/ResultWithToken.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/GetPostController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/model/GetPostListResponse.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/outbound/GetPostAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/outbound/ModifyPostAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/outbound/model-converters.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/GetPostUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/model/GetPostListResult.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/outbound/GetPostPort.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/service/GetPostService.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/service/SavePostService.kt
> feat: implement get post

- src/api/src/main/kotlin/com/tenmm/tilserver/category/adapter/inbound/rest/GetCategoryController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/category/adapter/inbound/rest/model/GetCategoriesResponse.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/category/application/inbound/GetCategoryUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/category/application/service/GetCategoryService.kt
> feat: impl category fin

- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/entity/AccountEntity.kt
- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/entity/DraftSyncEntity.kt
- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/repository/DraftSyncRepository.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/auth/domain/UserAuthInfo.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/common/utils/TimeUtils.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/draft/adapter/inbound/controller/GetDraftController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/draft/adapter/inbound/controller/SaveDraftController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/draft/adapter/inbound/controller/SyncDraftController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/draft/adapter/inbound/controller/model/GetDraftResponse.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/draft/adapter/inbound/scheduler/DraftSaveScheduler.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/draft/adapter/outbound/GetDraftAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/draft/adapter/outbound/SaveDraftAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/draft/adapter/outbound/SyncDraftAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/draft/adapter/outbound/model-converters.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/draft/application/inbound/SaveDraftUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/draft/application/inbound/SyncDraftUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/draft/application/outbound/SaveDraftPort.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/draft/application/outbound/SyncDraftPort.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/draft/application/service/GetDraftService.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/draft/application/service/SaveDraftService.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/draft/application/service/SyncDraftService.kt
> fix: modify draft logic

- .github/workflows/dev-api-deploy.yml
- build.gradle.kts
- script/start.sh
- src/api/build.gradle.kts
> feat: Add GitHubAction Deploy Script

- .github/workflows/dev-api-deploy.yml
> fix: push시점이 아닌 ,PR Closed + Merge로 변경

- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/entity/RefreshTokenEntity.kt
- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/repository/RefreshTokenRepository.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/auth/adapter/inboud/RefreshTokenController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/auth/adapter/inboud/model/RefreshTokenReqModel.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/auth/adapter/inboud/model/TokenResModel.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/auth/adapter/outbound/jwt/GetRefreshTokenAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/auth/adapter/outbound/jwt/SaveRefreshTokenAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/auth/application/jwt/GetRefreshTokenPort.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/auth/application/jwt/SaveRefreshTokenPort.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/auth/application/jwt/inbound/GenerateTokenUsecase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/auth/application/jwt/inbound/VerifyRefreshTokenUsecase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/auth/application/jwt/service/GenerateTokenService.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/auth/application/jwt/service/VerifyResfreshTokenService.kt
> Added: Refresh Token API 구현

- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/GetPostController.kt
> fix get post api

- src/api/src/main/kotlin/com/tenmm/tilserver/alarm/adapter/inbound/rest/GetAlarmController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/alarm/adapter/inbound/rest/ModifyAlarmController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/alarm/application/inbound/GetAlarmUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/alarm/application/service/GetAlarmService.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/alarm/domain/Alarm.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/auth/adapter/inboud/RefreshTokenController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/auth/adapter/outbound/jwt/SaveRefreshTokenAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/auth/application/jwt/service/GenerateTokenService.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/auth/application/jwt/service/VerifyResfreshTokenService.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/auth/application/service/OAuthLogInService.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/blog/adapter/inbound/rest/ModifyBlogController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/common/WebFluxConfig.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/common/security/annotation/RequiredAuthentication.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/common/security/annotation/UserArgumentResolver.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/draft/adapter/inbound/controller/GetDraftController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/draft/adapter/inbound/controller/SaveDraftController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/draft/adapter/inbound/controller/SyncDraftController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/user/adapter/inbound/GetUserMyProfileController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/user/adapter/inbound/ModifyUserProfileController.kt
- src/api/src/test/kotlin/com/tenmm/tilserver/alarm/adapter/TokenGenerateTest.kt
> impl resolver

- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/repository/AccountRepository.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/auth/adapter/outbound/persistence/SaveAccountAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/auth/application/inbound/ModifyAccountUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/auth/application/outbound/persistence/ModifyAccountPort.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/auth/application/service/ModifyAccountService.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/user/adapter/inbound/ModifyUserProfileController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/user/adapter/outbound/ModifyUserAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/user/application/inbound/ModifyUserUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/user/application/inbound/model/OnBoardingUserCommand.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/user/application/outbound/ModifyUserPort.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/user/application/service/ModifyUserService.kt
> impl mailing

- src/api/src/main/kotlin/com/tenmm/tilserver/account/adapter/inboud/rest/CertifyController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/account/adapter/inboud/rest/model/LogInResponse.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/account/adapter/outbound/google/GetGoogleOAuthAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/account/adapter/outbound/persistence/SaveAccountAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/account/application/inbound/GetOAuthUserInfoUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/account/application/inbound/LogInUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/account/application/inbound/LogOutUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/account/application/model/CreateAccountCommand.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/account/application/model/LogInCommand.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/account/application/model/LogInResult.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/account/application/model/OAuthTokenResult.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/account/application/model/OAuthUserInfo.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/account/application/outbound/GetOAuthTokenPort.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/account/application/outbound/GetOAuthUserInfoPort.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/account/application/outbound/SaveAccountPort.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/account/application/service/CertifyService.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/account/application/service/GetGoogleOAuthUserInfoService.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/common/security/annotation/UserArgumentResolver.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/security/adapter/outbound/SecurityTokenAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/security/application/inbound/DeleteTokenUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/security/application/inbound/ResolveTokenUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/security/application/outbound/DeleteSecurityTokenPort.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/security/application/service/DeleteTokenService.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/security/application/service/GenerateTokenService.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/security/application/service/ResolveTokenService.kt
> impl logout

- src/api/src/main/kotlin/com/tenmm/tilserver/common/security/annotation/UserArgumentResolver.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/model/GetPostListResponse.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/model/GetPostListResult.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/service/GetPostService.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/service/RecommendedPostService.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/domain/Post.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/security/application/service/GenerateTokenService.kt
> add profile img

- src/api/src/main/kotlin/com/tenmm/tilserver/account/adapter/inboud/rest/CertifyController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/common/config/rest/SwaggerConfig.kt
- Debuging용 CallBack Handler (AuthCode 가져오기 용)
- Swagger에 Jwt넣을 수 있는 Config 추가
> fix: Debugging AuthCode Callback, Swagger JWT

- src/api/src/main/kotlin/com/tenmm/tilserver/account/adapter/outbound/persistence/GetAccountAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/account/application/inbound/GetAccountUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/account/application/outbound/GetAccountPort.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/account/application/service/GetAccountService.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/common/config/redis/RedisConfig.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/user/adapter/inbound/GetUserMyProfileController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/user/adapter/inbound/model/GetMyProfileResponse.kt
> Fix user response model

- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/entity/PostEntity.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/outbound/GetPostAdapter.kt
> Modified: hitcount 증가 로직

- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/GetPostController.kt
> Fix timestamp

- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/entity/PostEntity.kt
- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/repository/PostRepository.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/outbound/GetPostAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/outbound/ModifyPostAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/outbound/GetPostPort.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/outbound/ModifyPostPort.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/service/GetPostService.kt
> fix post get logic

- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/repository/BlogRepository.kt
- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/repository/PostRepository.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/account/adapter/inboud/rest/model/LogOutResponse.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/blog/adapter/inbound/rest/ModifyBlogController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/blog/adapter/inbound/rest/model/DeleteBlogResponse.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/blog/adapter/inbound/rest/model/ModifyBlogRequest.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/blog/adapter/inbound/rest/model/SaveBlogRequest.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/blog/adapter/inbound/rest/model/SaveBlogResponse.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/SavePostController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/model/ConfirmUploadPostRequest.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/model/GetPostListResponse.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/model/GetPostMetaResponse.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/model/RequestUploadPostResponse.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/outbound/ModifyPostAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/user/adapter/inbound/ModifyUserProfileController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/user/adapter/inbound/model/ModifyUserRequest.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/user/adapter/inbound/model/OnBoardingUserRequest.kt
> fix trivial

- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/repository/PostRepository.kt
- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/repository/RecommendPostRepository.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/GetPostController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/model/GetPostListResponse.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/outbound/GetPostAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/outbound/RecommendedPostAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/GetPostUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/model/GetPostListResult.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/outbound/GetPostPort.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/outbound/GetRecommendedPostPort.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/service/GetPostService.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/service/RecommendedPostService.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/domain/Post.kt
fix: modify support to query post random
> fix: modify support to query post random

- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/repository/PostRepository.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/outbound/GetPostAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/outbound/GetPostPort.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/service/GetPostService.kt
> fix pageToken issue

- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/entity/ParsedPostEntity.kt
- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/repository/ParsedPostRepository.kt
- libs/storage/src/main/resources/sql/1. database_ddl.sql
- src/api/src/main/kotlin/com/tenmm/tilserver/crawler/adapter/outbound/PersistenceSaveCrawlingAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/crawler/adapter/outbound/RedisSaveCrawlingAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/outbound/PersistenceParsedPostAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/outbound/RedisParsedPostAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/outbound/model-converters.kt
> modify adapt to persistence

- .github/workflows/prd-api-deploy.yml
- ./gradlew 권한 변경
- jib task를 수행할 모듈 명시화
> fix: script

- .github/workflows/prd-api-deploy.yml
- src/api/src/main/kotlin/com/tenmm/tilserver/common/config/rest/SwaggerConfig.kt
- Swagger CORS 문제 (nginx - https, spring -http)
- 프로토콜 차이로 CORS문제 발생
> fix: Swagger CORS (via https)

- .github/workflows/prd-api-deploy.yml
- src/api/src/main/kotlin/com/tenmm/tilserver/security/application/service/DeleteTokenService.kt
- Delete Token 쪽에, @Transactional이 지정되지 않아 정상동작 (x)
- github action script 수정
> fix: Add @Transactional - Delete ExpireToken

- src/api/src/main/kotlin/com/tenmm/tilserver/blog/adapter/inbound/rest/GetBlogController.kt
> fix: modify get blog logic

- src/api/src/main/kotlin/com/tenmm/tilserver/user/adapter/outbound/UserAdapter.kt
fix add logic to modify user status complete
> fix add logic to modify user status complete

- .github/workflows/prd-api-deploy.yml
> fix: GitHub Action deploy script

- src/api/src/main/kotlin/com/tenmm/tilserver/crawler/adapter/outbound/DoCrawlingAdapter.kt
> Modified: velog created at 못 가져오는 문제 해결

- src/api/src/main/kotlin/com/tenmm/tilserver/crawler/adapter/outbound/DoCrawlingAdapter.kt
> Modified: 파싱 try-catch 구문 추가

- src/api/src/main/kotlin/com/tenmm/tilserver/user/application/service/ModifyUserService.kt
> fix path issue

- src/api/src/main/kotlin/com/tenmm/tilserver/user/application/service/ModifyUserService.kt
> solve issue 2

- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/model/GetPostListResponse.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/domain/Post.kt
- src/api/src/main/resources/application.yml
> fix: modify default profile img and add post response set name

- src/api/src/main/kotlin/com/tenmm/tilserver/account/adapter/inboud/rest/CertifyController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/account/adapter/outbound/google/GetGoogleOAuthAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/account/adapter/outbound/google/model/GoogleOAuthModel.kt
> fix: modify google oauth response model

- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/service/GetPostService.kt
> fix: solve npe problem

- libs/storage/src/main/resources/sql/1. database_ddl.sql
- src/api/src/main/kotlin/com/tenmm/tilserver/account/adapter/outbound/google/GetGoogleOAuthAdapter.kt
> fix: solve

- .github/workflows/prd-api-deploy.yml
- src/api/src/main/kotlin/com/tenmm/tilserver/common/config/rest/SwaggerConfig.kt
- prd에서 Swagger 제외
- git action prd script -> release 브랜치로
> feat: Prd 배포스크립트 & Swagger prd Profile설정

- .github/workflows/prd-api-deploy.yml
> fix: cd-script

- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/GetPostController.kt
> fix: modify search post logic

- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/outbound/GetPostAdapter.kt
> fix millisecond -> second

- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/model/ConfirmUploadPostResponse.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/model/PostSaveConfirmResult.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/service/SavePostService.kt
> Fix monthly publish logic

- .github/workflows/dev-api-deploy.yml
- .github/workflows/prd-api-deploy.yml
> fix: modify github wf

- src/api/src/main/kotlin/com/tenmm/tilserver/crawler/adapter/outbound/DoURLConnectionCrawlingAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/crawler/application/outbound/DoURLConnectionCrawlingPort.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/crawler/application/service/DoCrawlingService.kt
> #173 tistory 크롤링 문제 해결

- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/GetPostController.kt
> [BLBE-6] 게시글 카테고리 기반으로 가져오기 bug fix

- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/GetPostController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/service/GetPostService.kt
> Release/v1.1 (BLBE-6) 반영

- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/GetPostController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/outbound/GetPostAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/GetPostUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/outbound/GetPostPort.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/service/GetPostService.kt
> Release/1.1 <- [BLBE-6] CategoriyIdentifier 필수인자

- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/GetPostController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/outbound/GetPostAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/inbound/GetPostUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/outbound/GetPostPort.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/service/GetPostService.kt
> Release/v1.1 -> Dev 반영 (BLBE-6)

- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/inbound/rest/model/GetPostListResponse.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/adapter/outbound/GetPostAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/post/application/service/GetPostService.kt
> [BLBE-6] PageToken CategoryIdentifier Deprecated

- src/api/src/main/kotlin/com/tenmm/tilserver/common/config/properties/ProfileImgProperties.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/user/application/service/CreateUserService.kt
- src/api/src/main/resources/application-prd.yml
- src/api/src/main/resources/application.yml
> BLBE 5 :프로필 이미지 랜덤하게 내려주도록 수정

- libs/storage/src/main/resources/application-storage-dev.yml
- libs/storage/src/main/resources/application-storage-local.yml
> Modified: DML Update 제거

- src/api/src/main/kotlin/com/tenmm/tilserver/retrospect/adapter/inbound/DeleteRetrospectController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/retrospect/adapter/inbound/GetCategoryRetrospectController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/retrospect/adapter/inbound/GetRetrospectController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/retrospect/adapter/inbound/GetUserRetrospectController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/retrospect/adapter/inbound/PostRetrospectController.kt
> Modified: swagger 문구 수정, print, 주석제거

- src/api/src/main/kotlin/com/tenmm/tilserver/question/adapter/inbound/GetQuestionTypeController.kt
> Modified: 마지막 경로 슬래시 제거

- src/api/src/main/kotlin/com/tenmm/tilserver/retrospect/adapter/inbound/PostCategoryRetrospectController.kt
> Modified: 추천회고 업로드 에러코드 설명 수정

- src/api/src/main/kotlin/com/tenmm/tilserver/retrospect/adapter/inbound/Model/DetailRetrospect.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/retrospect/apllication/service/GetCategoryRetrospectService.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/retrospect/apllication/service/GetUserRetrospectService.kt
> Modified: 반환 필드 변결 (id -> retrospectIdentifier)

- src/api/src/main/kotlin/com/tenmm/tilserver/question/adapter/inbound/GetQuestionController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/question/adapter/inbound/GetQuestionTypeController.kt
> Modified: API 설명 추가

- src/api/src/main/kotlin/com/tenmm/tilserver/question/adapter/inbound/GetQuestionController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/question/application/inbound/GetQuestionUseCase.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/question/application/service/GetQuestionService.kt
> Modified: 전제 질문 내용 조회하는 API 추가

- src/api/src/main/kotlin/com/tenmm/tilserver/retrospect/adapter/inbound/DeleteRetrospectController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/retrospect/adapter/inbound/GetRetrospectController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/retrospect/adapter/inbound/Model/GetUserRetrospectResponseModel.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/retrospect/adapter/inbound/PostRetrospectController.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/retrospect/adapter/outbound/GetCategoryRetrospectAdapter.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/retrospect/apllication/service/GetCategoryRetrospectService.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/retrospect/apllication/service/GetUserRetrospectService.kt
> Modified: nextToken Null 처리

- src/api/src/main/kotlin/com/tenmm/tilserver/retrospect/adapter/inbound/GetRetrospectController.kt
> Modified: api설명 추가

- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/entity/QuestionEntity.kt
- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/entity/QuestionTypeEntity.kt
- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/entity/RecommendRetrospectEntity.kt
- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/entity/RetrospectEntity.kt
- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/entity/RetrospectQnaEntity.kt
- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/repository/QuestionRepository.kt
- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/repository/QuestionTypeRepository.kt
- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/repository/RecommendRetrospectRepository.kt
- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/repository/RetrospectQnaRepository.kt
- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/repository/RetrospectRepository.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/retrospect/adapter/inbound/Model/DetailRetrospect.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/retrospect/apllication/service/GetCategoryRetrospectService.kt
- src/api/src/main/kotlin/com/tenmm/tilserver/retrospect/apllication/service/GetUserRetrospectService.kt
> [BLBE-X] 프로필이미지 응답에 추가

- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/repository/RecommendRetrospectRepository.kt
- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/repository/RetrospectRepository.kt
> Modified: 정렬

- libs/storage/src/main/kotlin/com/tenmm/tilserver/outbound/persistence/repository/RecommendRetrospectRepository.kt
> Modified: 오류 발생
